name: Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: ./
    concurrency:
      group: npm-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install root node dependencies
        run: yarn

      - name: TypeScript
        run: yarn tsc

      - name: Lint
        run: yarn lint;

      - name: Run tests
        run: |
          sudo apt-get install -y xvfb
          xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' yarn test
